### ISSUE TITLE
Hangs when used over IMAP (mbsync)

### ISSUE THREAD

**Issue by VannTen** [moriyoshi/cyrus-sasl-xoauth2#3]
Hi.
I tried to use the plugin with mbsync, to connect over IMAP using xoauth2 mechanism.
Unfortunately, it hangs when trying to use the plugin, apparently
```
Connection is now encrypted
M: * OK Gimap ready for requests from 88.142.48.6 186mb276973608wmc
M: >>> 1 CAPABILITY
M: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH
M: 1 OK Thats all she wrote! 186mb276973608wmc
Logging in...
Authenticating with SASL mechanism XOAUTH2...
```
After that, it just stay there.
I don't think it is related to mbsync, the imap connection seems to work with another implementation
(https://github.com/robn/sasl2-oauth)
```
M: * OK Gimap ready for requests from 88.142.48.6 o8mb163401485wme
M: >>> 1 CAPABILITY
M: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH
M: 1 OK Thats all she wrote! o8mb163401485wme
Logging in...
Authenticating with SASL mechanism XOAUTH2...
M: >>> 2 AUTHENTICATE XOAUTH2 <token-redacted>
M: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS LITERAL- SPECIAL-USE APPENDLIMIT=35651584
M: 2 OK <email-redacted> authenticated (Success)
Error: SASL(-13): authentication failure: server rejected XOAUTH2: 
Warning: SASL reported failure despite successful IMAP authentication. Ignoring...
```
Well, there is also an error but it does work.

As the linked repo does not seem active, I'd reather user yours.

Would you have any pointers on what could cause that or on how I could debug it further ?
Thanks a lot :)

**Comment by moriyoshi** [comment]
I'm gonna take a look into this.

**Comment by moriyoshi** [comment]
This turned out to be a bug. Grab and build the latest on master to see if it's fixed.

**Comment by felixSchl** [comment]
Unreal, I just ran into this this morning and was about to submit a patch. Going through the process got me thinking if SASL_CB_USER and SASL_CB_AUTHNAME are used interchangeably, couldn't we check for either here? https://github.com/moriyoshi/cyrus-sasl-xoauth2/blob/6379368be6e984d41fd609f94208a32d28508afb/xoauth2_client.c#L192? With mbsync that avoids going around the loop one time. Not that it matters all that much I guess.

**Comment by moriyoshi** [comment]
@felixSchl 
> Going through the process got me thinking if SASL_CB_USER and SASL_CB_AUTHNAME are used interchangeably, couldn't we check for either here?

The initial patch (which doesn't appear in the commit history) actually did so when it was run with the special environment variable `SASL_XOAUTH2_ALSO_USE_USER_AS_AUTHNID` set to `"yes"`.  Later I figured out it used to work with Postfix because it provides client callbacks for  `SASL_CB_AUTHNAME` and `SASL_CB_USER` [1] and no SASL interactions should happen there, while mbsync fails to provide any client callbacks and passes credentials through an interaction loop.  As XOAUTH2 is an authentication process and the right callback in this context is `SASL_CB_AUTHNAME`, we need to go no futher than it for the first time.  This was simply a bug.

[1] https://github.com/vdukhovni/postfix/blob/af3d4ae2c3af1f999e2bb54cc449d7027dd8b853/postfix/src/xsasl/xsasl_cyrus_client.c#L309-L314 (for the authenticity of this unofficial mirror, look [here](https://groups.google.com/d/msg/mailing.postfix.users/6Kkel3J_nv4/fFWPVHDM9XUJ))

[2] https://sourceforge.net/p/isync/isync/ci/master/tree/src/drv_imap.c#l1935

**Comment by VannTen** [comment]
It is indeed fixed and works like a charm now.

Thanks a lot for your work /
